coverage:
  status:
    default_rules:
      carryforward_behavior: pass
    project:
      default:
        target: auto
      demo:
        target: auto
        flags:
          - demo
      index:
        target: auto
        flags:
          - index
        carryforward_behavior: exclude
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: yes
  require_head: yes       
  branches: null
  show_carryforward_flags: true

flags:
  demo:
    paths:
      - src/demo/demo.py
    carryforward: false
  index:
    paths:
      - src/index/index.py
    carryforward: true